name: Update Time

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行一次
  push:
    branches:
      - main

jobs:
  update-time:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get current time and write to file
      run: |
        echo "Current time: $(date)" >> current_time.txt

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add current_time.txt
        git commit -m 'Update current time'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
